name: Makefile CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:

    run-on: ubuntu-latest

    steps:
    -  uses: actions/checkout@v4

    - name: Fabrique Pickomino
      run: make
  
    